# Generated by Django 3.0.5 on 2020-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200426_1554'),
        ('course', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='like_users',
            field=models.ManyToManyField(related_name='like_users_file', to='login.User', verbose_name='用户'),
        ),
    ]
