# Generated by Django 3.0.5 on 2020-04-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sno', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('nickname', models.CharField(default='--', max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32)),
                ('institute', models.CharField(choices=[('chuan_jian', '船舶海洋与建筑工程学院'), ('ji_dong', '机械动力与工程学院'), ('dian_yuan', '电子信息与电气工程学院'), ('cai_liao', '材料科学与工程学院'), ('shu_xue', '数学科学学院'), ('wu_li', '物理与天文学院'), ('hua_xue', '化学化工学院'), ('sheng_ming', '生命科学技术学院'), ('sheng_yi_gong', '生物医学工程学院'), ('an_tai', '安泰经济与管理学院'), ('qi_ta', '其它')], max_length=256)),
                ('major', models.CharField(default='--', max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
