# Generated by Django 3.0.3 on 2020-03-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='未知', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='未知', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(choices=[('chuan_jian', '船舶海洋与建筑工程学院'), ('ji_dong', '机械动力与工程学院'), ('dian_yuan', '电子信息与电气工程学院'), ('cai_liao', '材料科学与工程学院'), ('shu_xue', '数学科学学院'), ('wu_li', '物理与天文学院'), ('hua_xue', '化学化工学院'), ('sheng_ming', '生命科学技术学院'), ('sheng_yi_gong', '生物医学工程学院'), ('an_tai', '安泰经济与管理学院'), ('qi_ta', '其它')], max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32),
        ),
    ]
