# Generated by Django 3.0.5 on 2020-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follow_+', to='login.User', verbose_name='关注'),
        ),
    ]
